apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginx-crashloop.fullname" . }}-nginx
  labels:
    {{ include "nginx-crashloop.nginx.labels" . | nindent 4 }}
data:
  nginx.conf: |+
    user www-data;
    worker_processes auto;
    pid /run/nginx.pid;
    #daemon off;
    events {
      worker_connections  1024;
    }
    http {
      gzip on;
      gzip_disable "msie6";
      include /etc/nginx/conf.d/*.conf;
      upstream flask {
        zone backend 64k;
        server {{ include "nginx-crashloop.fullname" . }}-flask:5000;
      }
      server {
         listen 80;
         server_name flasknginxtest.com;
         location / {
            proxy_pass http://flask; # 5000
            proxy_set_header Host  $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
      }
    }